name: insight_ed
description: "Insight Ed is an innovative mobile application designed to revolutionize the learning experience for visually impaired students in higher education."
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/insightEd.png
    - assets/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
